import {
  Injectable,
  Inject,
  NotFoundException,
  ForbiddenException,
  InternalServerErrorException,
  Logger,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { InjectQueue } from '@nestjs/bull';
import type { Queue } from 'bull';
import { Repository, Between } from 'typeorm';
import Redis from 'ioredis';
import { REDIS_CLIENT } from '../common/redis.module';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit');
import { Report, ReportType, ReportStatus } from './entities/report.entity';
import { Subscription } from '../subscriptions/entities/subscription.entity';
import { PaymentCard } from '../payment-cards/entities/payment-card.entity';
import { User } from '../users/entities/user.entity';

const PDF_TTL_SECONDS = 3600;

// ─── i18n strings ─────────────────────────────────────────────────────────
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    summary_report: 'Summary Report', detailed_report: 'Detailed Report', tax_report: 'Tax Report', audit_report: 'Audit Report',
    period: 'Period', generated: 'Generated', account: 'Account',
    overview: 'Overview', active_subs: 'active subscriptions', per_month: '/ month', per_year: '/ year (estimated)',
    by_category: 'By Category', subs: 'subs', top_subs: 'Top Subscriptions', by_status: 'By Status',
    subscriptions: 'Subscriptions', total: 'Total', name: 'Name', amount: 'Amount', category: 'Category',
    status: 'Status', plan: 'Plan', card: 'Card', started: 'Started', next_payment: 'Next payment', cancelled: 'Cancelled',
    tax_summary: 'Tax Summary', business_expenses: 'Business Expenses', personal_expenses: 'Personal Expenses',
    total_deductible: 'Total deductible', service: 'Service', period_col: 'Period',
    monthly: '/mo', yearly: '/yr', weekly: '/wk', quarterly: '/qtr', lifetime: 'lifetime', one_time: 'one-time',
    footer: 'Generated by SubRadar AI — subradar.ai',
    active: 'Active', trial: 'Trial', cancelled_status: 'Cancelled', paused: 'Paused',
    spending_chart: 'Spending by Category',
  },
  ru: {
    summary_report: 'Сводный отчёт', detailed_report: 'Детальный отчёт', tax_report: 'Налоговый отчёт', audit_report: 'Аудит',
    period: 'Период', generated: 'Сформирован', account: 'Аккаунт',
    overview: 'Обзор', active_subs: 'активных подписок', per_month: '/ мес', per_year: '/ год (оценка)',
    by_category: 'По категориям', subs: 'подп.', top_subs: 'Топ подписки', by_status: 'По статусу',
    subscriptions: 'Подписки', total: 'Итого', name: 'Название', amount: 'Сумма', category: 'Категория',
    status: 'Статус', plan: 'Тариф', card: 'Карта', started: 'Начало', next_payment: 'Следующий платёж', cancelled: 'Отменена',
    tax_summary: 'Налоговая сводка', business_expenses: 'Бизнес-расходы', personal_expenses: 'Личные расходы',
    total_deductible: 'Итого к вычету', service: 'Сервис', period_col: 'Период',
    monthly: '/мес', yearly: '/год', weekly: '/нед', quarterly: '/кв', lifetime: 'навсегда', one_time: 'разово',
    footer: 'Сформировано в SubRadar AI — subradar.ai',
    active: 'Активна', trial: 'Триал', cancelled_status: 'Отменена', paused: 'Приостановлена',
    spending_chart: 'Расходы по категориям',
  },
  kk: {
    summary_report: 'Жиынтық есеп', detailed_report: 'Толық есеп', tax_report: 'Салық есебі', audit_report: 'Аудит',
    period: 'Кезең', generated: 'Жасалды', account: 'Аккаунт',
    overview: 'Шолу', active_subs: 'белсенді жазылым', per_month: '/ ай', per_year: '/ жыл (болжам)',
    by_category: 'Санат бойынша', subs: 'жаз.', top_subs: 'Топ жазылымдар', by_status: 'Мәртебе бойынша',
    subscriptions: 'Жазылымдар', total: 'Барлығы', name: 'Атауы', amount: 'Сома', category: 'Санат',
    status: 'Мәртебе', plan: 'Тариф', card: 'Карта', started: 'Басталды', next_payment: 'Келесі төлем', cancelled: 'Тоқтатылды',
    tax_summary: 'Салық жиынтығы', business_expenses: 'Бизнес шығыстар', personal_expenses: 'Жеке шығыстар',
    total_deductible: 'Шегерімге жалпы', service: 'Сервис', period_col: 'Кезең',
    monthly: '/ай', yearly: '/жыл', weekly: '/апт', quarterly: '/тқс', lifetime: 'мәңгі', one_time: 'бір рет',
    footer: 'SubRadar AI арқылы жасалды — subradar.ai',
    active: 'Белсенді', trial: 'Сынақ', cancelled_status: 'Тоқтатылды', paused: 'Тоқтатылды',
    spending_chart: 'Санат бойынша шығыстар',
  },
};

function t(locale: string, key: string): string {
  return TRANSLATIONS[locale]?.[key] || TRANSLATIONS['en']?.[key] || key;
}

// ─── Colors ───────────────────────────────────────────────────────────────
const C = {
  primary: '#6C47FF',
  primaryLight: '#8B6AFF',
  green: '#10B981',
  red: '#EF4444',
  orange: '#F59E0B',
  text: '#1A1A1A',
  textLight: '#666666',
  textMuted: '#999999',
  border: '#E5E7EB',
  headerBg: '#6C47FF',
  rowEven: '#F9FAFB',
  white: '#FFFFFF',
};

const CATEGORY_COLORS: Record<string, string> = {
  STREAMING: '#E50914', MUSIC: '#1DB954', AI_SERVICES: '#10A37F', PRODUCTIVITY: '#3B82F6',
  GAMING: '#8B5CF6', DESIGN: '#A259FF', EDUCATION: '#F59E0B', FINANCE: '#059669',
  INFRASTRUCTURE: '#0071E3', SECURITY: '#4687FF', HEALTH: '#EF4444', SPORT: '#22C55E',
  DEVELOPER: '#24292E', NEWS: '#1A1A1A', BUSINESS: '#6366F1', OTHER: '#9CA3AF',
};

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(
    @InjectRepository(Report) private readonly reportRepo: Repository<Report>,
    @InjectRepository(Subscription) private readonly subRepo: Repository<Subscription>,
    @InjectRepository(PaymentCard) private readonly cardRepo: Repository<PaymentCard>,
    @InjectRepository(User) private readonly userRepo: Repository<User>,
    @InjectQueue('reports') private readonly reportQueue: Queue,
    @Inject(REDIS_CLIENT) private readonly redis: Redis,
  ) {}

  // ────────────────────────────────────────────────────────────
  // Public API
  // ────────────────────────────────────────────────────────────

  async generate(userId: string, from: string, to: string, type: ReportType, locale?: string): Promise<Report> {
    const user = await this.userRepo.findOne({ where: { id: userId } });
    if (user && user.plan === 'free') {
      const now = new Date();
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
      const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
      const count = await this.reportRepo.count({ where: { userId, createdAt: Between(monthStart, monthEnd) } });
      if (count >= 1) throw new ForbiddenException('Free plan allows 1 report per month. Upgrade to Pro for unlimited reports.');
    }

    const report = this.reportRepo.create({ userId, from, to, type, status: ReportStatus.PENDING });
    const saved = await this.reportRepo.save(report);
    await this.reportQueue.add('generate-pdf', { reportId: saved.id, userId, locale: locale || user?.locale || 'en' });
    return saved;
  }

  async findOne(userId: string, id: string): Promise<Report> {
    const report = await this.reportRepo.findOne({ where: { id } });
    if (!report) throw new NotFoundException('Report not found');
    if (report.userId !== userId) throw new ForbiddenException();
    return report;
  }

  async findAll(userId: string): Promise<Report[]> {
    return this.reportRepo.find({ where: { userId }, order: { createdAt: 'DESC' } });
  }

  async downloadPdf(userId: string, id: string): Promise<Buffer> {
    const report = await this.findOne(userId, id);
    if (report.status !== ReportStatus.READY) throw new NotFoundException(`Report is not ready yet (status: ${report.status})`);
    const base64 = await this.redis.get(`report:pdf:${id}`);
    if (!base64) throw new NotFoundException('PDF expired. Please regenerate.');
    return Buffer.from(base64, 'base64');
  }

  // ────────────────────────────────────────────────────────────
  // Processor entry point
  // ────────────────────────────────────────────────────────────

  async buildAndStorePdf(userId: string, reportId: string, locale = 'en'): Promise<void> {
    await this.reportRepo.update(reportId, { status: ReportStatus.GENERATING, error: null });
    try {
      const buffer = await this.buildPdf(userId, reportId, locale);
      await this.redis.set(`report:pdf:${reportId}`, buffer.toString('base64'), 'EX', PDF_TTL_SECONDS);
      await this.reportRepo.update(reportId, { status: ReportStatus.READY });
      this.logger.log(`PDF ready: report ${reportId}`);
    } catch (error) {
      this.logger.error(`PDF failed: report ${reportId}: ${error.message}`);
      await this.reportRepo.update(reportId, { status: ReportStatus.FAILED, error: error.message?.substring(0, 500) });
      throw error;
    }
  }

  // ────────────────────────────────────────────────────────────
  // PDF Builder
  // ────────────────────────────────────────────────────────────

  private async buildPdf(userId: string, id: string, locale: string): Promise<Buffer> {
    const report = await this.findOne(userId, id);
    const user = await this.userRepo.findOne({ where: { id: userId } });
    const cards = await this.cardRepo.find({ where: { userId } });
    const cardMap = Object.fromEntries(cards.map((c) => [c.id, c]));

    const subs = await this.subRepo.createQueryBuilder('s')
      .where('s.userId = :userId', { userId })
      .andWhere('(s.startDate IS NULL OR s.startDate <= :to)', { to: report.to })
      .andWhere('(s.cancelledAt IS NULL OR s.cancelledAt >= :from)', { from: report.from })
      .orderBy('s.amount', 'DESC')
      .getMany();

    // Pre-fetch icons
    const iconMap = new Map<string, Buffer>();
    await Promise.all(subs.filter((s) => s.iconUrl).slice(0, 30).map(async (s) => {
      const buf = await this.fetchIcon(s.iconUrl);
      if (buf) iconMap.set(s.id, buf);
    }));

    const l = locale.startsWith('ru') ? 'ru' : locale.startsWith('kk') ? 'kk' : 'en';

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' }) as any;
      const buffers: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const PW = 595.28;
      const ML = 50;
      const MR = 50;
      const CW = PW - ML - MR;

      const reportTitle = t(l, `${report.type.toLowerCase()}_report`);

      // ── Header ─────────────────────────────────────────────
      doc.rect(0, 0, PW, 90).fill(C.headerBg);
      doc.fontSize(24).font('Helvetica-Bold').fillColor(C.white).text('SubRadar', ML, 22, { continued: true });
      doc.fontSize(24).fillColor('rgba(255,255,255,0.5)').text(' AI');
      doc.fontSize(12).fillColor('rgba(255,255,255,0.9)').text(reportTitle, ML, 52);
      if (user) doc.fontSize(9).fillColor('rgba(255,255,255,0.7)').text(user.name || user.email, ML, 70, { align: 'right', width: CW });

      doc.fillColor(C.text);
      doc.y = 105;

      // ── Meta ───────────────────────────────────────────────
      doc.fontSize(9).fillColor(C.textMuted);
      doc.text(`${t(l, 'period')}: ${this.fmtDate(report.from, l)} — ${this.fmtDate(report.to, l)}`, ML);
      doc.text(`${t(l, 'generated')}: ${this.fmtDate(new Date().toISOString(), l)}`, ML, doc.y - 11, { align: 'right', width: CW });
      if (user?.email) doc.text(`${t(l, 'account')}: ${user.email}`, ML);
      doc.moveDown(1);
      doc.fillColor(C.text);

      // ── Content ────────────────────────────────────────────
      if (report.type === ReportType.SUMMARY) {
        this.pdfSummary(doc, subs, l, ML, CW);
      } else if (report.type === ReportType.DETAILED) {
        this.pdfDetailed(doc, subs, cardMap, iconMap, l, ML, CW);
      } else if (report.type === ReportType.TAX) {
        this.pdfTax(doc, subs, cardMap, l, ML, CW);
      } else {
        this.pdfSummary(doc, subs, l, ML, CW); // AUDIT fallback
      }

      // ── Footer ─────────────────────────────────────────────
      doc.moveDown(2);
      this.drawLine(doc, ML, CW);
      doc.fontSize(8).fillColor(C.textMuted).text(t(l, 'footer'), ML, doc.y + 4, { align: 'center', width: CW });

      doc.end();
    });
  }

  // ════════════════════════════════════════════════════════════
  // SUMMARY
  // ════════════════════════════════════════════════════════════

  private pdfSummary(doc: any, subs: Subscription[], l: string, ML: number, CW: number) {
    const active = subs.filter((s) => s.status === 'ACTIVE' || s.status === 'TRIAL');
    const totalMonthly = subs.reduce((s, sub) => s + this.monthly(sub), 0);
    const cur = subs[0]?.currency || 'USD';

    // ── Overview box ────────────────────
    const boxTop = doc.y;
    doc.rect(ML, boxTop, CW, 65).lineWidth(1).strokeColor(C.border).fillAndStroke(C.rowEven, C.border);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.text).text(t(l, 'overview'), ML + 14, boxTop + 8);
    doc.fontSize(22).fillColor(C.primary).text(`${cur} ${totalMonthly.toFixed(2)}`, ML + 14, boxTop + 24);
    doc.fontSize(10).font('Helvetica').fillColor(C.textLight).text(t(l, 'per_month'), ML + 160, boxTop + 30);
    doc.fontSize(10).fillColor(C.textMuted).text(`${active.length} ${t(l, 'active_subs')}  |  ${cur} ${(totalMonthly * 12).toFixed(0)} ${t(l, 'per_year')}`, ML + 14, boxTop + 48);
    doc.y = boxTop + 75;

    // ── Category chart (horizontal bars) ────────────────────
    const byCat: Record<string, { count: number; amount: number }> = {};
    subs.forEach((s) => {
      if (!byCat[s.category]) byCat[s.category] = { count: 0, amount: 0 };
      byCat[s.category].count++;
      byCat[s.category].amount += this.monthly(s);
    });
    const catSorted = Object.entries(byCat).sort((a, b) => b[1].amount - a[1].amount);
    const maxAmt = catSorted[0]?.[1].amount || 1;

    doc.moveDown(0.5);
    this.sectionTitle(doc, t(l, 'spending_chart'), ML);
    const chartTop = doc.y;
    const barH = 18;
    const barGap = 6;
    const labelW = 100;
    const barMaxW = CW - labelW - 80;

    catSorted.slice(0, 8).forEach(([cat, data], i) => {
      const y = chartTop + i * (barH + barGap);
      if (y > 700) return;
      const barW = Math.max(4, (data.amount / maxAmt) * barMaxW);
      const color = CATEGORY_COLORS[cat] || C.textMuted;
      // Label
      doc.fontSize(9).font('Helvetica').fillColor(C.text).text(cat, ML, y + 3, { width: labelW - 4 });
      // Bar
      doc.rect(ML + labelW, y, barW, barH).fill(color);
      // Amount
      doc.fontSize(9).fillColor(C.textLight).text(`${cur} ${data.amount.toFixed(0)}`, ML + labelW + barW + 6, y + 3);
    });
    doc.y = chartTop + Math.min(catSorted.length, 8) * (barH + barGap) + 10;

    // ── Top subscriptions table ─────────────────────────────
    this.sectionTitle(doc, t(l, 'top_subs'), ML);
    const cols = [
      { label: '#', w: 25 },
      { label: t(l, 'name'), w: 200 },
      { label: t(l, 'category'), w: 100 },
      { label: `${t(l, 'amount')} ${t(l, 'monthly')}`, w: CW - 325 },
    ];
    this.tableHeader(doc, cols, ML);
    subs.slice(0, 10).forEach((s, i) => {
      if (doc.y > 740) doc.addPage();
      this.tableRow(doc, [
        `${i + 1}`,
        s.name,
        s.category,
        `${s.currency} ${this.monthly(s).toFixed(2)}`,
      ], cols, ML, i);
    });

    // ── Status breakdown ────────────────────────────────────
    doc.moveDown(1);
    this.sectionTitle(doc, t(l, 'by_status'), ML);
    const byStatus: Record<string, number> = {};
    subs.forEach((s) => { byStatus[s.status] = (byStatus[s.status] || 0) + 1; });
    const statusLabels: Record<string, string> = {
      ACTIVE: t(l, 'active'), TRIAL: t(l, 'trial'),
      CANCELLED: t(l, 'cancelled_status'), PAUSED: t(l, 'paused'),
    };
    doc.fontSize(10).font('Helvetica');
    Object.entries(byStatus).forEach(([status, count]) => {
      const color = status === 'ACTIVE' ? C.green : status === 'TRIAL' ? C.orange : status === 'CANCELLED' ? C.red : C.textMuted;
      const y = doc.y;
      doc.circle(ML + 4, y + 5, 3).fill(color);
      doc.fillColor(C.text).text(`  ${statusLabels[status] || status}: ${count}`, ML + 10, y);
    });
  }

  // ════════════════════════════════════════════════════════════
  // DETAILED
  // ════════════════════════════════════════════════════════════

  private pdfDetailed(doc: any, subs: Subscription[], cardMap: Record<string, PaymentCard>, iconMap: Map<string, Buffer>, l: string, ML: number, CW: number) {
    const totalMonthly = subs.reduce((s, sub) => s + this.monthly(sub), 0);
    const cur = subs[0]?.currency || 'USD';

    this.sectionTitle(doc, `${t(l, 'subscriptions')} (${subs.length})  —  ${t(l, 'total')}: ${cur} ${totalMonthly.toFixed(2)}${t(l, 'monthly')}`, ML);

    const cols = [
      { label: t(l, 'name'), w: 130 },
      { label: t(l, 'amount'), w: 80 },
      { label: t(l, 'category'), w: 80 },
      { label: t(l, 'status'), w: 60 },
      { label: t(l, 'card'), w: 70 },
      { label: t(l, 'next_payment'), w: CW - 420 },
    ];
    this.tableHeader(doc, cols, ML);

    subs.forEach((s, i) => {
      if (doc.y > 730) { doc.addPage(); this.tableHeader(doc, cols, ML); }
      const card = s.paymentCardId ? cardMap[s.paymentCardId] : null;
      this.tableRow(doc, [
        s.name.substring(0, 20),
        `${s.currency} ${Number(s.amount).toFixed(2)}${this.periodLabel(s.billingPeriod, l)}`,
        s.category,
        s.status,
        card ? `••••${card.last4}` : '—',
        s.nextPaymentDate ? this.fmtDate(s.nextPaymentDate, l) : '—',
      ], cols, ML, i);
    });

    // Total row
    const totalY = doc.y;
    doc.rect(ML, totalY, CW, 22).fill(C.primary);
    doc.fontSize(10).font('Helvetica-Bold').fillColor(C.white);
    doc.text(t(l, 'total'), ML + 6, totalY + 5, { width: 130 });
    doc.text(`${cur} ${totalMonthly.toFixed(2)}${t(l, 'monthly')}`, ML + 130 + 6, totalY + 5, { width: 80 });
    doc.y = totalY + 28;
    doc.fillColor(C.text);
  }

  // ════════════════════════════════════════════════════════════
  // TAX
  // ════════════════════════════════════════════════════════════

  private pdfTax(doc: any, subs: Subscription[], cardMap: Record<string, PaymentCard>, l: string, ML: number, CW: number) {
    const business = subs.filter((s) => s.isBusinessExpense);
    const personal = subs.filter((s) => !s.isBusinessExpense);
    const bizTotal = business.reduce((s, sub) => s + Number(sub.amount), 0);
    const persTotal = personal.reduce((s, sub) => s + Number(sub.amount), 0);
    const cur = subs[0]?.currency || 'USD';

    // Summary box
    this.sectionTitle(doc, t(l, 'tax_summary'), ML);
    doc.fontSize(14).font('Helvetica-Bold').fillColor(C.green).text(`${cur} ${bizTotal.toFixed(2)}`, ML);
    doc.fontSize(10).font('Helvetica').fillColor(C.textLight).text(`${t(l, 'business_expenses')} (${business.length})`, ML);
    doc.moveDown(0.3);
    doc.fontSize(14).font('Helvetica-Bold').fillColor(C.text).text(`${cur} ${persTotal.toFixed(2)}`, ML);
    doc.fontSize(10).font('Helvetica').fillColor(C.textLight).text(`${t(l, 'personal_expenses')} (${personal.length})`, ML);
    doc.moveDown(1);

    // Business table
    if (business.length > 0) {
      this.sectionTitle(doc, t(l, 'business_expenses'), ML);
      const cols = [
        { label: t(l, 'service'), w: 150 },
        { label: t(l, 'category'), w: 100 },
        { label: t(l, 'amount'), w: 90 },
        { label: t(l, 'period_col'), w: 70 },
        { label: t(l, 'card'), w: CW - 410 },
      ];
      this.tableHeader(doc, cols, ML);
      business.forEach((s, i) => {
        if (doc.y > 730) { doc.addPage(); this.tableHeader(doc, cols, ML); }
        const card = s.paymentCardId ? cardMap[s.paymentCardId] : null;
        this.tableRow(doc, [
          s.name.substring(0, 22),
          s.category,
          `${s.currency} ${Number(s.amount).toFixed(2)}`,
          s.billingPeriod,
          card ? `••••${card.last4}` : '—',
        ], cols, ML, i);
      });

      // Total row
      const ty = doc.y;
      doc.rect(ML, ty, CW, 22).fill(C.green);
      doc.fontSize(10).font('Helvetica-Bold').fillColor(C.white);
      doc.text(`${t(l, 'total_deductible')}: ${cur} ${bizTotal.toFixed(2)}`, ML + 6, ty + 5, { width: CW - 12 });
      doc.y = ty + 30;
      doc.fillColor(C.text);
    }

    // Personal table
    if (personal.length > 0) {
      doc.moveDown(0.5);
      this.sectionTitle(doc, t(l, 'personal_expenses'), ML);
      doc.fontSize(9).font('Helvetica').fillColor(C.textLight);
      personal.forEach((s) => {
        if (doc.y > 740) doc.addPage();
        doc.fillColor(C.text).text(`${s.name}`, ML, doc.y, { continued: true, width: 200 });
        doc.fillColor(C.textMuted).text(`  ${s.category}`, { continued: true });
        doc.fillColor(C.text).text(`  ${s.currency} ${Number(s.amount).toFixed(2)}`, { align: 'right', width: CW - 300 });
      });
    }
  }

  // ════════════════════════════════════════════════════════════
  // Drawing helpers
  // ════════════════════════════════════════════════════════════

  private sectionTitle(doc: any, title: string, ML: number) {
    doc.moveDown(0.5);
    doc.fontSize(13).font('Helvetica-Bold').fillColor(C.text).text(title, ML);
    doc.moveDown(0.4);
  }

  private tableHeader(doc: any, cols: { label: string; w: number }[], ML: number) {
    const y = doc.y;
    doc.rect(ML, y, cols.reduce((s, c) => s + c.w, 0), 20).fill('#EEEEF5');
    doc.fontSize(8).font('Helvetica-Bold').fillColor(C.textLight);
    let x = ML;
    cols.forEach((col) => {
      doc.text(col.label.toUpperCase(), x + 6, y + 5, { width: col.w - 12 });
      x += col.w;
    });
    doc.y = y + 22;
  }

  private tableRow(doc: any, values: string[], cols: { label: string; w: number }[], ML: number, idx: number) {
    const y = doc.y;
    const totalW = cols.reduce((s, c) => s + c.w, 0);
    if (idx % 2 === 0) doc.rect(ML, y, totalW, 18).fill(C.rowEven);
    doc.fontSize(9).font('Helvetica').fillColor(C.text);
    let x = ML;
    values.forEach((val, i) => {
      const color = i === 0 && val.match(/^\d+$/) ? C.textMuted : C.text;
      doc.fillColor(color).text(val, x + 6, y + 4, { width: cols[i].w - 12 });
      x += cols[i].w;
    });
    doc.y = y + 18;
  }

  private drawLine(doc: any, ML: number, CW: number) {
    doc.moveTo(ML, doc.y).lineTo(ML + CW, doc.y).lineWidth(0.5).strokeColor(C.border).stroke();
    doc.moveDown(0.3);
  }

  // ════════════════════════════════════════════════════════════
  // Utilities
  // ════════════════════════════════════════════════════════════

  private async fetchIcon(url: string): Promise<Buffer | null> {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(3000) });
      if (!res.ok) return null;
      const ct = res.headers.get('content-type') || '';
      if (!ct.startsWith('image/')) return null;
      return Buffer.from(await res.arrayBuffer());
    } catch { return null; }
  }

  private monthly(sub: Subscription): number {
    const amt = Number(sub.amount) || 0;
    switch (sub.billingPeriod) {
      case 'YEARLY': return amt / 12;
      case 'QUARTERLY': return amt / 3;
      case 'WEEKLY': return amt * 4.33;
      default: return amt;
    }
  }

  private fmtDate(d?: string | Date | null, locale = 'en'): string {
    if (!d) return '—';
    const date = new Date(d);
    if (isNaN(date.getTime())) return '—';
    const loc = locale.startsWith('ru') ? 'ru-RU' : locale.startsWith('kk') ? 'kk-KZ' : 'en-US';
    return date.toLocaleDateString(loc, { year: 'numeric', month: 'short', day: 'numeric' });
  }

  private periodLabel(p: string, l = 'en'): string {
    const key = { MONTHLY: 'monthly', YEARLY: 'yearly', WEEKLY: 'weekly', QUARTERLY: 'quarterly', LIFETIME: 'lifetime', ONE_TIME: 'one_time' }[p] || p;
    return t(l, key);
  }
}
